### ISSUE TITLE
cheers!

### ISSUE THREAD

**Issue by deepthawtz** [nullstyle/go#8]
hey scott, hope you're doing well. I'm testing out this tipping bot, sorry if it looks like a phishing scam

@GitCash send 200000 satoshis to @nullstyle

**Comment by GitCash** [comment]
[![GitCash Tip Response](https://gitcash.io/tip/pic/193/image.png)](https://gitcash.io/claim/nullstyle)
@nullstyle

**Comment by nullstyle** [comment]
:)  no worries brother.  Hope allis going well your direction as well!

**Comment by deepthawtz** [comment]
woops, looks like bot failed me. try that again

@GitCash send 200000 satoshis to @nullstyle

**Comment by GitCash** [comment]
[![GitCash Tip Response](https://gitcash.io/tip/pic/202/image.png)](https://gitcash.io/claim/nullstyle)
@nullstyle

**Comment by deepthawtz** [comment]
damn, bot not able to comment for some reason. oh well can claim at http://gitcash.io/claim/nullstyle
